// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Defines data required to fetch paginated data
type Pagination struct {
	// Page number for which data will be fetched
	Page int `json:"page"`
	// Number of data to be fetched
	Limit int `json:"limit"`
}

type Article struct {
	ID        string                         `json:"id"`
	Title     *string                        `json:"title"`
	Content   *string                        `json:"content"`
	Image     *string                        `json:"image"`
	CreatedAt *string                        `json:"createdAt"`
	Author    *ListArticleResponseDataAuthor `json:"author"`
}

type CreateArticleRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Image   string `json:"image"`
}

type CreateArticleResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type ListArticleRequest struct {
	Keyword    string      `json:"keyword"`
	LastID     string      `json:"lastId"`
	Pagination *Pagination `json:"pagination"`
}

type ListArticleResponse struct {
	Code int                      `json:"code"`
	Msg  string                   `json:"msg"`
	Data *ListArticleResponseData `json:"data"`
}

type ListArticleResponseData struct {
	Total    int        `json:"total"`
	Articles []*Article `json:"articles"`
}

type ListArticleResponseDataAuthor struct {
	ID       *string `json:"id"`
	Username *string `json:"username"`
}
