// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/web.proto

package web

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Web service

func NewWebEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Web service

type WebService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Web_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Web_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Web_BidiStreamService, error)
}

type webService struct {
	c    client.Client
	name string
}

func NewWebService(name string, c client.Client) WebService {
	return &webService{
		c:    c,
		name: name,
	}
}

func (c *webService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Web.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webService) ClientStream(ctx context.Context, opts ...client.CallOption) (Web_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Web.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &webServiceClientStream{stream}, nil
}

type Web_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type webServiceClientStream struct {
	stream client.Stream
}

func (x *webServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *webServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *webServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *webService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Web_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Web.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &webServiceServerStream{stream}, nil
}

type Web_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type webServiceServerStream struct {
	stream client.Stream
}

func (x *webServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *webServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *webServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webService) BidiStream(ctx context.Context, opts ...client.CallOption) (Web_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Web.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &webServiceBidiStream{stream}, nil
}

type Web_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type webServiceBidiStream struct {
	stream client.Stream
}

func (x *webServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *webServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *webServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *webServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Web service

type WebHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Web_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Web_ServerStreamStream) error
	BidiStream(context.Context, Web_BidiStreamStream) error
}

func RegisterWebHandler(s server.Server, hdlr WebHandler, opts ...server.HandlerOption) error {
	type web interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Web struct {
		web
	}
	h := &webHandler{hdlr}
	return s.Handle(s.NewHandler(&Web{h}, opts...))
}

type webHandler struct {
	WebHandler
}

func (h *webHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.WebHandler.Call(ctx, in, out)
}

func (h *webHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.WebHandler.ClientStream(ctx, &webClientStreamStream{stream})
}

type Web_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type webClientStreamStream struct {
	stream server.Stream
}

func (x *webClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *webHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WebHandler.ServerStream(ctx, m, &webServerStreamStream{stream})
}

type Web_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type webServerStreamStream struct {
	stream server.Stream
}

func (x *webServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *webHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.WebHandler.BidiStream(ctx, &webBidiStreamStream{stream})
}

type Web_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type webBidiStreamStream struct {
	stream server.Stream
}

func (x *webBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *webBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
