// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"auth/store/mongo"
	"go-micro.dev/v4"
)

// Injectors from wire.go:

func WireAuthHandler(service micro.Service) *authHandler {
	userStore := mongo.NewUserStore()
	handlerAuthHandler := NewAuthHandler(service, userStore)
	return handlerAuthHandler
}
