// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"article/store/mongo"
	"go-micro.dev/v4"
)

// Injectors from wire.go:

func WireArticleHandler(service micro.Service) *articleHandler {
	articleStore := mongo.NewArticleStore()
	handlerArticleHandler := NewArticle(service, articleStore)
	return handlerArticleHandler
}
